//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Host.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterStudent", ReplyAction="http://tempuri.org/IService1/RegisterStudentResponse")]
        string RegisterStudent(OnlineAdmissionService1.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterStudent", ReplyAction="http://tempuri.org/IService1/RegisterStudentResponse")]
        System.Threading.Tasks.Task<string> RegisterStudentAsync(OnlineAdmissionService1.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidateUser", ReplyAction="http://tempuri.org/IService1/ValidateUserResponse")]
        string ValidateUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidateUser", ReplyAction="http://tempuri.org/IService1/ValidateUserResponse")]
        System.Threading.Tasks.Task<string> ValidateUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Merit", ReplyAction="http://tempuri.org/IService1/MeritResponse")]
        OnlineAdmissionService1.getmerit Merit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Merit", ReplyAction="http://tempuri.org/IService1/MeritResponse")]
        System.Threading.Tasks.Task<OnlineAdmissionService1.getmerit> MeritAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Host.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Host.ServiceReference1.IService1>, Host.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RegisterStudent(OnlineAdmissionService1.Student s) {
            return base.Channel.RegisterStudent(s);
        }
        
        public System.Threading.Tasks.Task<string> RegisterStudentAsync(OnlineAdmissionService1.Student s) {
            return base.Channel.RegisterStudentAsync(s);
        }
        
        public string ValidateUser(string username, string password) {
            return base.Channel.ValidateUser(username, password);
        }
        
        public System.Threading.Tasks.Task<string> ValidateUserAsync(string username, string password) {
            return base.Channel.ValidateUserAsync(username, password);
        }
        
        public OnlineAdmissionService1.getmerit Merit() {
            return base.Channel.Merit();
        }
        
        public System.Threading.Tasks.Task<OnlineAdmissionService1.getmerit> MeritAsync() {
            return base.Channel.MeritAsync();
        }
    }
}
